class Theme:
    panel_title = "default"
    heading = "bold yellow"
    table_field = "bold bright_magenta"
    table_value = "none"
    inline_stat = "cyan"
    vendor_list = "cyan"
    nameserver_list = "cyan"
    disclaimer = "italic white on red"
    tags = "default"
    port_info = "dim yellow"
    footer = "cyan"
    info = "bold green"
    warn = "bold yellow"
    error = "bold red"
